import test from 'node:test';
import { request as httpRequest } from 'node:http';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../src/server.mjs';
import { PROFILE } from '../src/ledger.mjs';
async function start(options={}) {const server=createApp(options);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}`;return {server,url,post:(path,body,headers={})=>fetch(url+path,{method:'POST',headers:{Origin:url,'Content-Type':'application/json',...headers},body:JSON.stringify(body)}),close:()=>new Promise(resolve=>{server.closeAllConnections();server.close(resolve);})};}
test('HTTP create, partial, confirm, duplicate, reorg, export and restart persistence',async()=>{
  const directory=mkdtempSync(join(tmpdir(),'usdt-invoice-test-'));const options={storageFile:join(directory,'ledger.json')};let app=await start(options);
  try{const response=await app.post('/api/invoices',{client:'Sintetic HTTP',amount:'0.3',expiresAt:new Date(Date.now()+3600000).toISOString()});assert.equal(response.status,200);const {invoiceId}=await response.json();const pay={invoiceId,transactionId:'sim-http-1',amount:'0.1',confirmations:0,network:PROFILE.network,token:PROFILE.token,recipient:PROFILE.recipient};assert.equal((await app.post('/api/observations',pay)).status,200);pay.confirmations=3;await app.post('/api/observations',pay);assert.equal((await (await app.post('/api/observations',pay)).json()).duplicate,true);let exported=await (await fetch(app.url+'/api/export')).json();assert.equal(exported.simulation,true);assert.equal(exported.invoices[0].confirmed,'0.100000');assert.equal(exported.invoices[0].status,'partial');assert.equal(exported.journal.length,3);pay.confirmations=1;await app.post('/api/observations',pay);await app.close();app=await start(options);exported=await (await fetch(app.url+'/api/state')).json();assert.equal(exported.invoices[0].remaining,'0.300000');assert.equal(exported.invoices[0].status,'confirming');}finally{await app.close();rmSync(directory,{recursive:true,force:true});}
});
test('host/origin and JSON boundary reject hostile requests',async()=>{const app=await start();try{assert.equal((await app.post('/api/invoices',{}, {Origin:'https://evil.example'})).status,403);assert.equal((await app.post('/api/invoices',{}, {'Content-Type':'text/plain'})).status,403);const hostileHost=await new Promise((resolve,reject)=>{const req=httpRequest(app.url+'/api/state',{headers:{Host:'evil.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(hostileHost,403);assert.equal((await fetch(app.url+'/api/invoices',{method:'POST',headers:{Origin:app.url,'Content-Type':'application/json'},body:'{bad'})).status,400);assert.equal((await app.post('/api/invoices',{client:'x'.repeat(17000)})).status,413);}finally{await app.close();}});
test('HTML simulation, CSP, export download, missing route',async()=>{const app=await start();try{const response=await fetch(app.url);const html=await response.text();assert.match(html,/SIMULARE LOCALĂ/);assert.match(response.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal((await fetch(app.url+'/missing')).status,404);assert.match((await fetch(app.url+'/api/export')).headers.get('content-disposition'),/attachment/);}finally{await app.close();}});
