import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { WdkReadOnlyVerifier,TRANSFER_TOPIC } from '../src/wdk-readonly.mjs';
import { TestnetStore } from '../src/testnet-store.mjs';
import { TESTNET,ReadOnlyRpc } from '../src/testnet-rpc.mjs';
import { createApp } from '../src/server.mjs';

const recipient='0x'+'2'.repeat(40), sender='0x'+'3'.repeat(40), tx='0x'+'a'.repeat(64), blockHash='0x'+'b'.repeat(64);
const hex=value=>'0x'+BigInt(value).toString(16),word=value=>'0x'+BigInt(value).toString(16).padStart(64,'0');
const timestamp=Date.parse('2026-10-04T10:00:00Z')/1000;
function setup(){
  const log={address:TESTNET.token,topics:[TRANSFER_TOPIC,'0x'+'0'.repeat(24)+sender.slice(2),'0x'+'0'.repeat(24)+recipient.slice(2)],data:word(40000000),logIndex:'0x0',transactionHash:tx,blockHash,blockNumber:'0x64',removed:false};
  const data={chain:hex(TESTNET.chainId),code:'0x1234',decimals:word(6),head:'0x66',receipt:{status:'0x1',transactionHash:tx,blockNumber:'0x64',blockHash,logs:[log]},block:{number:'0x64',hash:blockHash,timestamp:hex(timestamp)},failure:false,calls:[]};
  const rpc={request:async({method,params=[]})=>{
    data.calls.push(method);if(data.failure)throw new Error('https://rpc.example/?apiKey=SYNTHETIC_RPC_SECRET');
    const values={eth_chainId:data.chain,eth_getCode:data.code,eth_blockNumber:data.head,eth_getTransactionReceipt:data.receipt,eth_getBlockByNumber:data.block};
    if(method==='eth_call')return params[0].data==='0x313ce567'?data.decimals:word(123000000);
    if(!Object.hasOwn(values,method))throw new Error('write attempted');return structuredClone(values[method]);
  }};
  const verifier=new WdkReadOnlyVerifier({rpc,recipient});
  const store=new TestnetStore({recipient,clock:()=>Date.parse('2026-10-04T10:10:00Z')});
  const invoiceInput={client:'Client Testnet Sintetic',amount:'100',validFrom:'2026-10-04T09:00:00.000Z',expiresAt:'2026-10-04T11:00:00.000Z'};
  const invoiceId=store.createInvoice(invoiceInput);
  return {data,rpc,verifier,store,invoiceInput,input:{invoiceId,transactionHash:tx,logIndex:0},snapshot:()=>store.snapshot().invoices[0]};
}
test('official WDK address/balance reads no signing or send methods used',async()=>{const f=setup();try{const profile=await f.verifier.profile();assert.equal(profile.balanceUnits,'123000000');assert.equal(profile.wdkAddress.toLowerCase(),recipient);assert.equal(profile.wdkVersion,'1.0.0-beta.20');assert.ok(f.data.calls.includes('eth_call'));assert.ok(!f.data.calls.some(method=>/send|sign/i.test(method)));}finally{f.store.close();}});
test('verified event uses integer micro-units, chain/hash/logIndex key and explicit invoice',async()=>{const f=setup();try{await f.store.verify(f.verifier,f.input);assert.equal(f.snapshot().confirmed,'40.000000');assert.equal(f.snapshot().status,'partial');assert.equal(f.snapshot().observations[0].key,`${TESTNET.chainId}:${tx}:0`);}finally{f.store.close();}});
for(const [name,change,code] of [
  ['failed receipt',f=>{f.data.receipt.status='0x0';},'EVENT_UNAVAILABLE'],
  ['wrong token',f=>{f.data.receipt.logs[0].address=sender;},'EVENT_UNAVAILABLE'],
  ['wrong recipient',f=>{f.data.receipt.logs[0].topics[2]='0x'+'0'.repeat(24)+sender.slice(2);},'EVENT_UNAVAILABLE'],
  ['mainnet chain',f=>{f.data.chain='0x1';},'CHAIN'],
  ['wrong decimals',f=>{f.data.decimals=word(18);},'DECIMALS'],
  ['missing bytecode',f=>{f.data.code='0x';},'TOKEN'],
  ['malformed event amount',f=>{f.data.receipt.logs[0].data='0x1';},'RPC_DATA'],
  ['wrong transaction identity',f=>{f.data.receipt.transactionHash='0x'+'c'.repeat(64);},'RPC_DATA'],
  ['duplicate logIndex in receipt',f=>{f.data.receipt.logs.push(f.data.receipt.logs[0]);},'RPC_DATA'],
  ['wrong log block hash',f=>{f.data.receipt.logs[0].blockHash='0x'+'c'.repeat(64);},'RPC_DATA'],
  ['missing receipt',f=>{f.data.receipt=null;},'EVENT_UNAVAILABLE'],
  ['removed log',f=>{f.data.receipt.logs[0].removed=true;},'EVENT_UNAVAILABLE']
])test(`testnet rejects ${name}`,async()=>{const f=setup();try{change(f);await assert.rejects(()=>f.store.verify(f.verifier,f.input),{code});assert.equal(f.snapshot().confirmed,'0.000000');assert.equal(f.store.snapshot().journal.length,1);}finally{f.store.close();}});
test('multiple logs selected explicitly, same tx can contain two distinct payments',async()=>{const f=setup();try{f.data.receipt.logs.push({...f.data.receipt.logs[0],data:word(60000000),logIndex:'0x1'});await f.store.verify(f.verifier,f.input);await f.store.verify(f.verifier,{...f.input,logIndex:1});assert.equal(f.snapshot().status,'paid');assert.equal(f.snapshot().observations.length,2);}finally{f.store.close();}});
test('exact duplicate and increasing confirmations never double credit',async()=>{const f=setup();try{await f.store.verify(f.verifier,f.input);assert.equal((await f.store.verify(f.verifier,f.input)).duplicate,true);f.data.head='0x80';await f.store.verify(f.verifier,f.input);assert.equal(f.snapshot().confirmed,'40.000000');assert.equal(f.snapshot().observations.length,1);}finally{f.store.close();}});
test('same event cannot be assigned to second invoice even after reorg',async()=>{const f=setup();try{await f.store.verify(f.verifier,f.input);f.data.receipt=null;await f.store.verify(f.verifier,f.input);const invoiceId=f.store.createInvoice({...f.invoiceInput,client:'Al doilea demo'});f.data.receipt={status:'0x1',transactionHash:tx,blockNumber:'0x64',blockHash,logs:[{address:TESTNET.token,topics:[TRANSFER_TOPIC,'0x'+'0'.repeat(24)+sender.slice(2),'0x'+'0'.repeat(24)+recipient.slice(2)],data:word(40000000),logIndex:'0x0',transactionHash:tx,blockHash,blockNumber:'0x64'}]};await assert.rejects(()=>f.store.verify(f.verifier,{...f.input,invoiceId}),{code:'DUPLICATE_ASSIGNMENT'});assert.equal(f.store.snapshot().invoices[1].confirmed,'0.000000');}finally{f.store.close();}});
test('decreased confirmations retract credit without removing reserved event',async()=>{const f=setup();try{await f.store.verify(f.verifier,f.input);f.data.head='0x64';await f.store.verify(f.verifier,f.input);assert.equal(f.snapshot().confirmed,'0.000000');assert.equal(f.snapshot().pending,'40.000000');}finally{f.store.close();}});
test('confirmation journal preserves actual old/new numbers for UI and restart',async()=>{const f=setup();try{await f.store.verify(f.verifier,f.input);f.data.head='0x64';await f.store.verify(f.verifier,f.input);const entry=f.store.snapshot().journal.at(-1);assert.equal(entry.event,'CONFIRMATIONS_UPDATED');assert.equal(entry.previousConfirmations,3);assert.equal(entry.confirmations,1);}finally{f.store.close();}});
for(const reason of ['missing','failed','block changed','log disappears'])test(`reorganization withdraws credit: ${reason}`,async()=>{const f=setup();try{await f.store.verify(f.verifier,f.input);if(reason==='missing')f.data.receipt=null;if(reason==='failed')f.data.receipt.status='0x0';if(reason==='block changed')f.data.block.hash='0x'+'c'.repeat(64);if(reason==='log disappears')f.data.receipt.logs=[];await f.store.verify(f.verifier,f.input);assert.equal(f.snapshot().confirmed,'0.000000');assert.equal(f.snapshot().observations[0].canonical,false);assert.equal(f.store.snapshot().journal.at(-1).event,'CREDIT_REVOKED');}finally{f.store.close();}});
test('canonical reappearing event restores once; no extra observation',async()=>{const f=setup();try{await f.store.verify(f.verifier,f.input);const receipt=f.data.receipt;f.data.receipt=null;await f.store.verify(f.verifier,f.input);f.data.receipt=receipt;await f.store.verify(f.verifier,f.input);assert.equal(f.snapshot().confirmed,'40.000000');assert.equal(f.snapshot().observations.length,1);}finally{f.store.close();}});
test('canonical anchor changes during read: no credit is created',async()=>{const f=setup();try{const previous=f.rpc.request;let blocks=0;f.rpc.request=async args=>{const result=await previous(args);if(args.method==='eth_getBlockByNumber'&&++blocks===2)result.hash='0x'+'c'.repeat(64);return result;};await assert.rejects(()=>f.store.verify(f.verifier,f.input),{code:'EVENT_UNAVAILABLE'});assert.equal(f.snapshot().confirmed,'0.000000');}finally{f.store.close();}});
test('testnet verification fails closed without server configuration',async()=>{const server=createApp();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/testnet/state`);assert.equal(response.status,503);assert.equal((await response.json()).error,'TESTNET_DISABLED');}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}});
test('block timestamp outside explicit invoice interval retained without credit',async()=>{const f=setup();try{f.data.block.timestamp=hex(timestamp+7200);await f.store.verify(f.verifier,f.input);assert.equal(f.snapshot().confirmed,'0.000000');assert.equal(f.snapshot().observations[0].eligible,false);}finally{f.store.close();}});
test('block timestamp, not HTTP observation time, qualifies historical invoice',async()=>{const f=setup();try{f.data.block.timestamp=hex(timestamp-3600);await f.store.verify(f.verifier,f.input);assert.equal(f.snapshot().confirmed,'40.000000');}finally{f.store.close();}});
test('RPC error sanitized and does not impersonate reorg',async()=>{const f=setup();try{await f.store.verify(f.verifier,f.input);f.data.failure=true;await assert.rejects(()=>f.store.verify(f.verifier,f.input),problem=>problem.code==='RPC_UNAVAILABLE'&&!problem.message.includes('SYNTHETIC_RPC_SECRET')&&!problem.message.includes('rpc.example'));assert.equal(f.snapshot().confirmed,'40.000000');assert.ok(!JSON.stringify(f.store.snapshot()).includes('SYNTHETIC_RPC_SECRET'));}finally{f.store.close();}});
test('concurrent duplicate verification serialized with exactly one credit',async()=>{const f=setup();try{await Promise.all([f.store.verify(f.verifier,f.input),f.store.verify(f.verifier,f.input)]);assert.equal(f.snapshot().confirmed,'40.000000');assert.equal(f.store.snapshot().journal.length,2);}finally{f.store.close();}});
test('restart preserves events, journal and unique assignment; changed profile refused',async()=>{const f=setup();const directory=mkdtempSync(join(tmpdir(),'invoice-wdk-'));const file=join(directory,'testnet.sqlite');let store=new TestnetStore({file,recipient});try{const invoiceId=store.createInvoice(f.invoiceInput);await store.verify(f.verifier,{...f.input,invoiceId});store.close();store=new TestnetStore({file,recipient});assert.equal(store.snapshot().invoices[0].confirmed,'40.000000');assert.equal((await store.verify(f.verifier,{...f.input,invoiceId})).duplicate,true);assert.throws(()=>new TestnetStore({file,recipient:sender}),{code:'PROFILE_STORAGE'});}finally{store.close();f.store.close();rmSync(directory,{recursive:true,force:true});}});
test('SQLite rollback keeps event and journal atomic when journal insert fails',async()=>{const f=setup();const directory=mkdtempSync(join(tmpdir(),'invoice-rollback-'));const file=join(directory,'testnet.sqlite');const store=new TestnetStore({file,recipient});try{const invoiceId=store.createInvoice(f.invoiceInput);const db=new DatabaseSync(file);db.exec("CREATE TRIGGER fail_journal BEFORE INSERT ON journal BEGIN SELECT RAISE(ABORT,'synthetic persistence failure'); END;");db.close();await assert.rejects(()=>store.verify(f.verifier,{...f.input,invoiceId}));assert.equal(store.snapshot().observations.length,0);assert.equal(store.snapshot().journal.length,1);}finally{store.close();f.store.close();rmSync(directory,{recursive:true,force:true});}});
test('RPC boundary denies broadcast/signing and disallows invalid endpoint',async()=>{const rpc=new ReadOnlyRpc();for(const method of ['eth_sendRawTransaction','eth_sendTransaction','eth_sign','personal_sign'])await assert.rejects(()=>rpc.request({method}),{code:'RPC_WRITE_DENIED'});assert.throws(()=>new ReadOnlyRpc({url:'http://localhost:1234'}),{code:'RPC_CONFIG'});});
test('HTTP modes isolated; arbitrary RPC and manual confirmations rejected',async()=>{const f=setup();const server=createApp({testnet:{store:f.store,verifier:f.verifier}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;const post=(path,body)=>fetch(base+path,{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify(body)});try{assert.equal((await post('/api/testnet/profile',{rpcUrl:'https://hostile.example'})).status,400);assert.equal((await post('/api/testnet/verify',{...f.input,confirmations:100})).status,400);const response=await post('/api/testnet/verify',f.input);assert.equal(response.status,200);const simulation=await (await fetch(base+'/api/state')).json();assert.equal(simulation.invoices.length,0);const exported=await (await fetch(base+'/api/testnet/export')).json();assert.equal(exported.readOnly,true);assert.equal(exported.simulation,false);assert.equal(exported.invoices[0].confirmed,'40.000000');assert.ok(!JSON.stringify(exported).includes('rpcUrl'));}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}});
